//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Store.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_MemberRole
    {
        public int MemberRoleID { get; set; }
        public Nullable<int> memberId { get; set; }
        public Nullable<int> RoleId { get; set; }
    }
}
