//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Store.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_SlideImage
    {
        public int SlideId { get; set; }
        public string SlideTitle { get; set; }
        public string SlideImage { get; set; }
    }
}
